### Get all persons
GET http://localhost:3001/api/persons

### Create person
POST http://localhost:3001/api/persons
Content-Type: application/json

{"name": "name", "number": "number"}

### Create person, name missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{"noname": "name", "number": "number"}

### Create person, number missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{"name": "name"}

### Create person, name and number missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{"nonumber": "number"}

### Get person
GET http://localhost:3001/api/persons/1

### Get person, malformed id
GET http://localhost:3001/api/persons/text

### Get person, non-existing id
GET http://localhost:3001/api/persons/999

### Delete person
DELETE http://localhost:3001/api/persons/1

### Delete person, malformed id
DELETE http://localhost:3001/api/persons/text

### Delete person, non-existing id
DELETE http://localhost:3001/api/persons/999

### Update person
PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{"name": "name", "number": "number"}

### Update person, malformed id
PUT http://localhost:3001/api/persons/text
Content-Type: application/json

{"name": "name", "number": "number"}

### Update person, name missing
PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{"number": "number"}

### Update person, number missing
PUT http://localhost:3001/api/persons/1
Content-Type: application/json

{"name": "name", "nonumber": "number"}

### Update person, non-existing id
PUT http://localhost:3001/api/persons/999
Content-Type: application/json

{"name": "name", "number": "number"}